source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/PlanetAdDevelopers/Specs.git'

platform :ios, '12.0'

target 'SKPAdBenefitSampleApp' do

use_frameworks!
inhibit_all_warnings!

   pod 'SKPAdBenefit', '1.4.1'

# for test
   pod 'SDWebImage',   '~> 5.0'
   pod 'Toast',        '~> 4.0.0'
end
