source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/PlanetAdDevelopers/Specs.git'

platform :ios, '10.0'

target 'SKPAdBenefitSampleApp' do

use_frameworks!
inhibit_all_warnings!

   pod 'SKPAdBenefit', '=1.1.0'
   pod 'SDWebImage',   '~> 5.0'
   pod 'Toast',        '~> 4.0.0'
end
